services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      USER: "samba"
      PASS: "secret"
      RW: true      # Optional, default true
      UID: 1000    # Optional, default 1000
      GID: 1000    # Optional, default 1000
      MULTI_USER: false
    ports:
      - 445:445
    volumes:
      - /home/example:/storage
